# Generated by Django 5.2.4 on 2025-07-23 19:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The name of the role (e.g., 'Admin', 'Citizen')", max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(help_text='The country of the location', max_length=100)),
                ('city', models.CharField(help_text='The city of the location', max_length=100)),
                ('county', models.CharField(help_text='The county/region of the location', max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['country', 'city', 'county'],
                'unique_together': {('country', 'city', 'county')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the user joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='api_user_groups', related_query_name='api_user', to='auth.group', verbose_name='groups')),
                ('location', models.ForeignKey(blank=True, help_text='The geographical location of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.location')),
                ('role', models.ForeignKey(blank=True, help_text='The role of the user within the platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_user_permissions', related_query_name='api_user_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-joined_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='A concise title for the issue', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the issue')),
                ('category', models.CharField(help_text="The category of the issue (e.g., 'Infrastructure', 'Environment')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the issue was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the issue was last updated')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', help_text='The current status of the issue', max_length=20)),
                ('votes', models.IntegerField(default=0, help_text='The number of upvotes/support for the issue')),
                ('affected_locations', models.ManyToManyField(blank=True, help_text='Locations affected by this issue', related_name='issues_affected', to='api.location')),
                ('user', models.ForeignKey(help_text='The user who reported this issue', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.user')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The content of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the comment was created')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='The parent comment if this is a reply, otherwise null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('issue', models.ForeignKey(help_text='The issue this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.issue')),
                ('user', models.ForeignKey(help_text='The user who posted this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
