# Generated by Django 5.2.4 on 2025-07-24 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the announcement', max_length=255)),
                ('description', models.TextField(help_text='The description of the announcement')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the announcement was made')),
                ('user', models.ForeignKey(help_text='The user who posted this announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
