# Generated by Django 5.2.4 on 2025-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='issue_reference',
            field=models.CharField(blank=True, help_text='The issue that is referenced in this announcement, if any', max_length=255, null=True),
        ),
    ]
