# Generated by Django 5.2.5 on 2025-08-07 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_county_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['county__name', 'city__name', 'county__name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('country', 'city', 'county')},
        ),
    ]
