# Generated by Django 5.2.5 on 2025-08-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_location_options_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='affected_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations affected by this issue', null=True, related_name='issues_affected', to='api.location'),
        ),
    ]
